name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to newer version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # Updated to newer version

    - name: Build and push Docker image
      uses: docker/build-push-action@v3 # Updated to newer version
      with:
        context: .
        file: Dockerfile # Corrected file name
        push: false
        load: true
        tags: user/app:latest

    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker

    - name: Apply Kubernetes Configurations
      run: |
        minikube kubectl -- apply -f deployment.yaml
        minikube kubectl -- apply -f newapp-service.yaml
